import type { Metadata } from "next";
import { DM_Serif_Display, Inter, Noto_Sans_Arabic } from "next/font/google";
import { twJoin } from "tailwind-merge";
import "./globals.css";
import Sidenav from "@/components/Sidenav";

const arabic = Noto_Sans_Arabic({
  subsets: ["arabic"],
  variable: "--font-arabic",
});

const serif = DM_Serif_Display({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-serif",
});

export const metadata: Metadata = {
  title: "Personal Finance App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={twJoin(
          "grid lg:grid-cols-[250px_1fr] xl:grid-cols-[350px_1fr]",
          arabic.variable,
          serif.variable,
        )}
      >
        <Sidenav />
        <div className="w-full px-4 md:px-10 font-arabic">{children}</div>
      </body>
    </html>
  );
}
